### ISSUE TITLE
Incorrect characters in Vietnamese

### ISSUE THREAD

**Issue by torn4dom4n** [delucis/astro-og-canvas#57]
Hello, I followed the guide on [Add Open Graph images to Starlight](https://hideoo.dev/notes/starlight-og-images) by @HiDeoo  to my site to add og-image. However, I encountered some incorrect characters in Vietnamese. Here is an example:

![image](https://github.com/delucis/astro-og-canvas/assets/27698189/a8419286-7ca4-43c9-907a-73fc39ecc111)

The correct text should be `Động học siêu âm Doppler`.

I suspect this is a bug because Noto Sans is the default font and it should support Vietnamese characters.

**Comment by delucis** [comment]
By default we include a URL to download the basic Latin version of Noto Sans from [Fontsource](https://fontsource.org/fonts/noto-sans/cdn), but I think that font is a subset and doesn’t include the full Vietnamese character set:

https://github.com/delucis/astro-og-canvas/blob/733a77b4a0688b0ad2a44862258307f6452b26de/packages/astro-og-canvas/src/generateOpenGraphImage.ts#L84

Noto Sans supports many languages, but you often still need to specify extra files to include those outside of the default Latin character set.

I think, if you added `https://api.fontsource.org/v1/fonts/noto-sans/vietnamese-400-normal.ttf` for example to the `fonts` array in options, it should work.

As an example, you might like to check out the [config used by Astro’s Docs](https://github.com/withastro/docs/blob/af5edea59bc00aaf36263756070823d4971cf6e6/src/pages/open-graph/%5B...path%5D.ts#L70-L92), which includes multiple fonts for the different languages we need to support (in this case they are paths to local files instead of URLs to remote font files).

**Comment by torn4dom4n** [comment]
Thanks @delucis, I found a lot of information after this. So it's time to close this issue.
